apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflowab comit
on:
  workflow_dispatch:
    inputs:
      pickList:
        type: choice
        options:
          - abc
          - def
          - ghi
        default: abc
        required: true
        description: Pick list desciption
  push:
    branches:
      - main
jobs:
  my-job-1:
    outputs:
      output1: ${{ steps.step1.outputs.greeting }}
      output2: ${{ steps.step2.outputs.greeting }}
    steps:
      - name: My first step
        uses: docker://alpine:3.18
        id: step1
        run: |
          echo "pickList is '${{ inputs.pickList }}'"
