apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflowab comit
on:
  workflow_dispatch:
    inputs:
      value1:
        type: number
        required: true
        default: 9223372036854775807

jobs:
  my-job-1:
    steps:
      - name: My first step
        uses: docker://alpine:3.18
        id: step1
        run: |
          echo "boo'"
